Vagrant.configure("2") do |c|
  c.vm.define :default do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_check_update = true

    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "/usr/local/ghq/github.com", "/usr/local/ghq/github.com"

    # config.vm.network "forwarded_port", guest: 8080, host: 8080

    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 12
      vb.memory = (1024 * 8).to_s
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
    SHELL

    config.disksize.size = '120GB'
  end

  c.vm.define :groovy do |config|
    config.vm.box = "ubuntu/groovy64"
    config.vm.box_check_update = true

    config.vm.synced_folder ".", "/vagrant"
    config.vm.synced_folder "/usr/local/ghq/github.com", "/usr/local/ghq/github.com"

    config.vm.network "forwarded_port", guest: 8080, host: 8080

    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 15
      vb.memory = (1024 * 8).to_s
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
    SHELL

    config.disksize.size = '120GB'
  end
end
